name: F5XC AWS Cloud CE Vault module v0.11.23
on: workflow_dispatch
jobs:
  aws-cloud-ce-vault-module-destroy:
    runs-on: ubuntu-latest
    needs: [aws-cloud-ce-vault-module-reapply]
    steps:
      - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "The value of your release is ${{ github.ref }} and your release is  ${{ github.release }}."
      - name: Check out release and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout support repo
        uses: actions/checkout@v3
        with:
          repository: cklewar/f5-xc-test
          path: f5-xc-cert
          token:  ${{ secrets.GH_PAT }}
      - run: echo "The  ${{ github.release }} release has been cloned to the runner."
      - name: List files in the release
        run: |
          ls -la ${{ github.workspace }}
      - name: List files in the cert release
        run: |
          ls -la ${{ github.workspace }}/f5-xc-cert
      - name: Setup Terraform
        id: setup_tf
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
        continue-on-error: true
      - name: Terraform Init
        id: init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
        run: |
          cd ${{ github.workspace }}/ec2
          terraform init -upgrade
          cd ${{ github.workspace }}/vault 
          terraform init -upgrade
          cd ${{ github.workspace }}/ce
          cp main.tf.example main.tf
          terraform init -upgrade
      - name: Terraform Destroy
        id: destroy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
          VES_P12_PASSWORD: ${{ secrets.VES_P12_PASSWORD }}
          TF_VAR_f5xc_api_url: ${{ secrets.F5XC_API_URL }}
          TF_VAR_f5xc_api_p12_file_nfv: ${{ secrets.F5XC_API_P12_FILE_NFV }}
          TF_VAR_f5xc_api_p12_file: ${{ secrets.F5XC_API_P12_FILE }}
          TF_VAR_f5xc_api_p12_file_absolute: ${{ secrets.F5XC_API_P12_FILE_ABSOLUTE }}
          TF_VAR_f5xc_tenant: ${{ secrets.F5XC_TENANT }}
          TF_VAR_f5xc_api_token: ${{ secrets.F5XC_API_TOKEN }}
          TF_VAR_f5xc_api_credential_password: ${{ secrets.F5XC_API_CREDENTIAL_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY_FILE }}
          TF_VAR_ssh_private_key_file_absolute: ${{ secrets.SSH_PRIVATE_KEY_FILE_ABSOLUTE }}
          TF_VAR_ssh_public_key_file: ${{ secrets.SSH_PUBLIC_KEY_FILE }}
          TF_VAR_ssh_public_key_file_absolute: ${{ secrets.SSH_PUBLIC_KEY_FILE_ABSOLUTE }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_root_path: ${{ github.workspace }}
          TFE_TOKEN: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
        run: |
          cd ${{ github.workspace }}/ec2
          terraform destroy -auto-approve -no-color
          echo "VAULT_ADDR=http://$(terraform output -json | jq -r '.ssh_host.value'):8200" >> $GITHUB_ENV
          echo ${{ env.VAULT_ADDR }}
          cd ${{ github.workspace }}/vault
          terraform destroy -auto-approve -no-color
          cd ${{ github.workspace }}/ce
          cp main.tf.example main.tf
          terraform destroy -auto-approve -no-color
        continue-on-error: false
      - name: Cleanup environment
        id: cleanup_env
        run: |
          cd ${{ github.workspace }}/ce
          rm main.tf
      - run: echo "This job's status is ${{ job.status }}."